### ISSUE TITLE
range distance is 0

### ISSUE THREAD

**Issue by AntoineDubois** [omidvarnia/RangeEn#2]
Hi Guys,
Thank you for improving the signal randomness measure

When I use the function **RangeEn_A**, the denominator np.max(np.abs(x - y), axis=1) + np.min(np.abs(x - y), axis=1) in the function **dist_range** has some zeros and slowdown the computation by a lot.
What would you advise me?
Best wishes,

**Comment by omidvarnia** [comment]
Hi Antoine

Based on the mathematical definition of **_RangeEn_A_**, it is highly likely that the measure leads to undefined values at small tolerance values of r (see https://www.mdpi.com/1099-4300/20/12/962/htm for more details - see also Figures 3, 6, and 7 of the paper as examples of _**RangeEn_A**_ with undefined values at small _**r**_). If you need _**RangeEn**_ to be well-defined across the entire range of _**r**_, I would suggest to use _**RangeEn_B**_ instead.

Cheers;
Amir
